resources/connexionsg/_posts/2022-03-22-post-#TIL Importance of Water.md
resources/connexionsg/_posts/2022-03-29-post-#TIL Singapore's Core Foreign Policy Principles.md

Updated connexionsg posts for Mar 2022

Updated ConnexionSG posts - Mar

---

_economy/Case Studies/jurong-from-swamp-to-suburb.md
_economy/growing-our-economy/1979-to-1984-economic-restructuring.md
_economy/growing-our-economy/1986-to-1996-rebounding-into-a-decade-of-growth.md
_economy/growing-our-economy/the-1970s-upgrading-the-economy.md
_economy/surviving-our-independence/1959-1965-early-economic-strategies.md
_economy/surviving-our-independence/1965-1970-singapores-development-plan.md

To replace on a later date with new content!

Removing some photos

---

_economy/Case Studies/jurong-from-swamp-to-suburb.md
resources/resource-packages/_posts/2022-06-14-post-NE Insights on Disinformation and Influence Campaigns.md

update the resource package as req by MHA and edit a case study in Econ sector where I spotted two typos

Updates on resource packages and Economy sector

---

resources/resource-packages/_posts/2022-06-14-post-NE Insights on Disinformation and Influence Campaigns.md

Update on Resource package

---

resources/resource-packages/_posts/2022-10-08-post-Resources on Influence Campaigns.md

Fixed the broken link for the discussion package

Update link for pdf file 

---

pages/contact-us.md

Updated ConnexionSG FB and IG under contact us tab

Updated ConnexionSG FB and IG under contact us tab

---

resources/connexionsg/_posts/2023-02-18-post-#TD Food Security in Singapore.md

Hi, 
Changes incorporated. Re-submitting pls.
Thanks. 
Regards
Uma

Pull Request Resubmitted - with changes incorporated 

---

resources/news-in-focus/_posts/2023-02-24-post-Issue 02 2023.md

updated NiF

---

_social-national-identity/case-studies/unesco-bids-and-our-heritage.md

Re-send - UNESCO bids

---

pages/terms-of-use.md

Updated Terms of Use page

---

resources/resource-packages/_posts/2022-10-08-post-Resources on Influence Campaigns.md

…igns.md","fileName":"2022-10-08-post-Resources on Influence Campaigns.md","userId":"2052"}

Update Resources on Influence Campaigns

---

resources/resource-packages/_posts/2023-06-22-post-SAF Day 2023.md

…"2023-06-22-post-SAF Day 2023.md","userId":"487"}

Updated html links for SAF Day 2023

---

resources/resource-packages/_posts/2023-07-31-post-National Day 2023.md

…ame":"2023-07-31-post-National Day 2023.md","userId":"320"}

Update National Day Package page 

---

_foreign-policy/Expanding Our International Space/The Economic Space.md
_foreign-policy/Expanding Our International Space/The Geopolitical Space.md
_foreign-policy/Our Challenges/Singapore in a Diverse World.md
_foreign-policy/Our Challenges/Singapore in a HyperConnected World.md
_foreign-policy/Safeguarding our Sovereignty and National Interests.md
index.md
resources/resource-packages/_posts/2023-07-31-post-National Day 2023.md

Update Foreign Policy Chapter

---

_foreign-policy/Our Challenges/Singapore in a Diverse World.md
_foreign-policy/Safeguarding our Sovereignty and National Interests.md

<Re-sent>Update Foreign Policy Chapter

---

resources/resource-packages/_posts/2022-10-08-post-Resources on Influence Campaigns.md

…igns.md","fileName":"2022-10-08-post-Resources on Influence Campaigns.md","userId":"487"}

Included 3 FICA CXSG posts to Influence Campaigns page

---

resources/resource-packages/_posts/2023-10-26-post-Resource Page for The Conflict in the Middle East.md

Resource Page on Conflict in the Middle East

---

resources/resource-packages/_posts/2023-10-26-post-Resource Page for The Conflict in the Middle East.md

Update Resource page

---

_social-national-identity/building-a-multicultural-singapore.md

Amended grammatical changes in social sector

Amended grammatical changes in social sector

---

index.md

SAF Day 2024 

---

resources/resource-packages/_posts/2024-06-24-post-SAF Day 2024.md

SAF Day 2024 Resource package

---

resources/resource-packages/_posts/2024-02-15-post-Total Defence Resources.md

Hi Leslie, can you help to review the TDSB edits pls.

Edits to TD Sandbox

---

_data/footer.yml
pages/about-us.md

The Nexus email add was not working properly. Have fixed this.

Fixed broken link on About Us page

---

index.md

Removed the banner from homepage that asks users to zoom out in order to see the search icon

Removed the banner from homepage 
